<?xml version="1.0" encoding="UTF-8"?><testrun name="DaoFactoryTest" project="usermanagement" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="ua.nure.cs.kondratiuk.usermanagement.db.DaoFactoryTest" time="0.001">
    <testcase name="testGetDao" classname="ua.nure.cs.kondratiuk.usermanagement.db.DaoFactoryTest" time="0.001">
      <error>java.lang.ExceptionInInitializerError&#13;
	at ua.nure.cs.kondratiuk.usermanagement.db.DaoFactoryTest.testGetDao(DaoFactoryTest.java:16)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:124)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
Caused by: java.lang.NullPointerException&#13;
	at java.util.Properties$LineReader.readLine(Unknown Source)&#13;
	at java.util.Properties.load0(Unknown Source)&#13;
	at java.util.Properties.load(Unknown Source)&#13;
	at ua.nure.cs.kondratiuk.usermanagement.db.DaoFactory.&lt;init&gt;(DaoFactory.java:17)&#13;
	at ua.nure.cs.kondratiuk.usermanagement.db.DaoFactory.&lt;clinit&gt;(DaoFactory.java:12)&#13;
	... 19 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
